layout_spectrum: 0.2082540807314217
typography_spectrum: 0.9152404896449298
color:
  brandStrength: 0.788098796736449
  lightness: 0.44124566996470094
  saturation: 0.745225589023903
  rhythmicContrast: 0.510094030527398
  brandColors:
    - '#F22F7E'
    - '#F57851'
    - '#FFFFFF'
    - '#F890BA'
    - '#AA0055'
name: SOLAXAI
navigation:
  - name: TWITCH.TV
    url: 'https://www.twitch.tv/solaxai'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/shilinliu/'
    type: external
